version: 2

updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - java
      - exclude release notes

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github actions
      - exclude release notes
