queue_rules:
  - name: default
    queue_conditions:
      - "author=dependabot[bot]"
      - "check-success=build"
      - "check-success=native-linux"
      - "check-success=native-macos"
      - "check-success=native-windows"
    merge_conditions:
      - "check-success=build"
      - "check-success=native-linux"
      - "check-success=native-macos"
      - "check-success=native-windows"
    update_method: rebase

