pull_request_rules:
  - name: "Merge strict with rebase if Dependabot"
    conditions:
      - "author=dependabot[bot]"
      - "check-success=build"
      - "check-success=native-linux"
      - "check-success=native-macos"
      - "check-success=native-windows"
    actions:
      merge:
        strict: true
        strict_method: rebase
        method: merge

  - name: "Delete if merged"
    conditions:
      - merged
    actions:
      delete_head_branch: { }
