pull_request_rules:
  - name: "Rebase if non-draft, unreviewed"
    conditions:
      - "-draft"
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "check-success=build"
      - "check-success=native-linux"
      - "check-success=native-macos"
      - "check-success=native-windows"
      - "check-success=SonarCloud Code Analysis"
    actions:
      rebase: { }

  - name: "Merge strict with rebase if non-draft, reviewed"
    conditions:
      - "-draft"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "check-success=build"
      - "check-success=native-linux"
      - "check-success=native-macos"
      - "check-success=native-windows"
      - "check-success=SonarCloud Code Analysis"
    actions:
      merge:
        strict: true
        strict_method: rebase
        method: merge

  - name: "Delete if merged"
    conditions:
      - merged
    actions:
      delete_head_branch: { }
